### ISSUE TITLE
Liberar as pastas vistas

### ISSUE THREAD

**Issue by Joaopedroslv** [lucaspedronet/curso-ecmas6-news-features#57]

**Comment by Joaopedroslv** [comment]
por favor

**Comment by lucaspedronet** [comment]
### ESSE REPOSITÓRIO TEM A FINALIDADE DIDÁTICA APENAS. @Joaopedroslv 

> Seu intuido é que os alunos façam seu projetos sem consultar nenhum repositório, apenas o livro.

**Comment by lucaspedronet** [comment]
## Fechando issues
